---
title: "ML_only"
output: pdf_document
---

```{r setup, echo = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ape)
library(ggtree)
library(knitr)
library(phytools)
library(tidyverse)
library(magrittr)
```

```{r fig.width=15, fig.height = 200, include = FALSE} 
  tree_global = read.tree('RAxML_bipartitions.result_FIN4_raw_rooted_wBoots_4098mam1out_OK.newick')
  n_tips = length(tree_global$tip.label)
  root_node = tree_global$edge[(!tree_global$edge[,1] %in% tree_global$edge[,2]),1] %>% unique()
  root_age = max( dist.nodes(tree_global)[,root_node] )
  
  label_offset = 0.02 * root_age
  tree_width = 5 * root_age
```

```{r, include = FALSE}
## drop all the non-relevant tips

charstate = read.csv('1128_Completedata.csv') 
charstate
charstate = charstate%>%mutate(Average = as.numeric(Average))

tips <- tree_global$tip.label
tips_short = str_replace(tips, "[A-Z_]+$", "")
tree_global$tip.label = tips_short

tip_names = data.frame(Name_long=tips, Name=tips_short)
charstate %<>% left_join(tip_names)

missing_in_charstate = tree_global$tip.label[! tree_global$tip.label %in% charstate$Name]
 
tree_global = ape::drop.tip(tree_global, missing_in_charstate)

charstate %<>% filter(!is.na(Name_long))

rank <- match( charstate[,1], tree_global$tip.label )

charstate = charstate[match( tree_global$tip.label, charstate[,1] ), ] #the data order matches, checked manually as well.

 if(! all( charstate[,1] ==tree_global$tip.label ) ){
      stop("Error: tip labels and dataframe rows not in same order!")
    }

```




```{r, echo = FALSE}

litter_ancestral_ML = 
  ace(
  charstate$Average, 
  tree_global,
  type = "continuous",
  method = "ML",
  model = "BM"
)


litter_ancestral_pic =
  ace(
  charstate$Average,
  tree_global,
  type = "continuous",
  method = "pic",
  model = "BM"
)

litter_ancestral_REML = 
  ace(
  charstate$Average, 
  tree_global,
  type = "continuous",
  method = "REML",
  model = "BM"
)

```
Plotting various data
```{r, echo = FALSE} 

# Plot PIC over REML
A_methods = data.frame(
  pic = litter_ancestral_pic$ace, 
  reml = litter_ancestral_REML$ace
)

# Add node numbers to the data frame
A_methods$node = seq(1:nrow(A_methods)) + n_tips
A_methods %>%
  ggplot(aes(x = reml,y = pic)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, color = "blue") + coord_fixed()
```

``` {r, echo = FALSE}
# Plot ML over REML
B_methods = data.frame(
  ml = litter_ancestral_ML$ace, 
  reml = litter_ancestral_REML$ace
)

# Add node numbers to the data frame
B_methods$node = seq(1:nrow(A_methods)) + n_tips
B_methods %>%
  ggplot(aes(x = reml,y = ml)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, color = "blue") + 
  coord_fixed()
```